package sistema;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSuiteAutenthicationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCLOG1() {
    driver.get("http://localhost:8080/BookPad_war//BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("emaildiprova@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("provaprova");
    driver.findElement(By.cssSelector(".btn-1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".error-mex"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCLOG2() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(992, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("anna@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Passwordprovaerrata");
    driver.findElement(By.cssSelector(".btn-1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".error-mex"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCLOG3() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("anna@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Anna2000!!");
    driver.findElement(By.cssSelector(".btn-1")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Logout"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG1() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 900));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("ciaociao.it");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".em"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG2() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("lino_");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("anna@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Anna2000!");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("Anna2000!");
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".error-mex"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG3() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("lino_");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lino@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("ci");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("ci");
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".pa"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG8() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("utenteprova");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("utenteprova@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("utenteProva2");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("utenteProva2");
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Logout"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG4() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("lino_");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lino@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("ciaoatuttimondo");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("ciaoatuttimondo");
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".pa"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG5() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("lino_");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lino@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Anna2000!");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("Anna2000!!");
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".pa2"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG6() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lino@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Lino2000!");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("Lino2000!");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.cssSelector("div:nth-child(12)")).click();
    driver.findElement(By.id("sub")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".us"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCREG7() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Registrati")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("lino@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Lino2000!");
    driver.findElement(By.id("paswd2")).click();
    driver.findElement(By.id("paswd2")).sendKeys("Lino2000!");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ciaociao___");
    driver.findElement(By.id("sub")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".us"));
      assert(elements.size() > 0);
    }
  }
}
