package sistema;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSuitePubStoriaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lOGIN() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("anna@gmail.com");
    driver.findElement(By.cssSelector("div > form")).click();
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Anna2000!!");
    driver.findElement(By.cssSelector(".btn-1")).click();
  }
  @Test
  public void tCPUB1() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Scrivi")).click();
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Titolo storia di Giovanninooooooooooooooooooooooooooooooooooooooooo");
    vars.put("count", driver.findElement(By.cssSelector(".tit > span")).getText());
    System.out.println(vars.get("count").toString());
    vars.put("countInt", js.executeScript("return parseInt(arguments[0]);", vars.get("count")));
    System.out.println(vars.get("countInt").toString());
    vars.put("result", js.executeScript("return arguments[0]>60", vars.get("countInt")));
    assertEquals(vars.get("result").toString(), "true");
  }
  @Test
  public void tCLOG2() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(992, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("anna@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("Passwordprovaerrata");
    driver.findElement(By.cssSelector(".btn-1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".error-mex"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCLOG1() {
    driver.get("http://localhost:8080/BookPad_war//BookPad_war/");
    driver.manage().window().setSize(new Dimension(999, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("emaildiprova@gmail.com");
    driver.findElement(By.id("paswd")).click();
    driver.findElement(By.id("paswd")).sendKeys("provaprova");
    driver.findElement(By.cssSelector(".btn-1")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".error-mex"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tCPUB2() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Scrivi")).click();
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("Titoloesempio");
    driver.findElement(By.id("trama")).click();
    driver.findElement(By.id("pb_story")).click();
    vars.put("count", driver.findElement(By.cssSelector(".tr > span")).getText());
    vars.put("countInt", js.executeScript("return parseInt(arguments[0]);", vars.get("count")));
    vars.put("result", js.executeScript("return (arguments[0]>0)", vars.get("count")));
    assertEquals(vars.get("result").toString(), "false");
  }
  @Test
  public void tCPUB7() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Scrivi")).click();
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("L\'Alba");
    driver.findElement(By.id("trama")).click();
    driver.findElement(By.id("trama")).sendKeys("trama prova");
    driver.findElement(By.name("chap_title")).click();
    driver.findElement(By.name("chap_title")).sendKeys("Primo incontro");
    driver.findElement(By.name("chap_text")).click();
    driver.findElement(By.cssSelector(".box:nth-child(2)")).click();
    driver.findElement(By.id("pb_story")).click();
    vars.put("count", driver.findElement(By.cssSelector(".ch_txt > span")).getText());
    vars.put("result", js.executeScript("return (arguments[0]>0)", vars.get("count")));
    assertEquals(vars.get("result").toString(), "false");
  }
  @Test
  public void tCPUB5() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Scrivi")).click();
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("L\'Alba");
    driver.findElement(By.id("trama")).click();
    driver.findElement(By.id("trama")).sendKeys("tramaprova");
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("trama")).click();
    driver.findElement(By.name("chap_text")).click();
    driver.findElement(By.name("chap_text")).sendKeys("ggggggggggCapitolo1");
    driver.findElement(By.cssSelector(".capitolo > label:nth-child(2)")).click();
    driver.findElement(By.name("chap_title")).click();
    driver.findElement(By.id("pb_story")).click();
    vars.put("count", driver.findElement(By.cssSelector(".ch_tit > span")).getText());
    vars.put("countInt", js.executeScript("return parseInt(arguments[0]);", vars.get("count")));
    vars.put("result", js.executeScript("return (arguments[0]>0)", vars.get("count")));
    assertEquals(vars.get("result").toString(), "false");
  }
  @Test
  public void tCPUB8() {
    driver.get("http://localhost:8080/BookPad_war/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Scrivi")).click();
    driver.findElement(By.id("titolo")).click();
    driver.findElement(By.id("titolo")).sendKeys("TitoloEsempip9");
    driver.findElement(By.id("trama")).click();
    driver.findElement(By.id("trama")).sendKeys("Trama prova");
    driver.findElement(By.name("chap_title")).click();
    driver.findElement(By.name("chap_title")).sendKeys("Titolo1");
    driver.findElement(By.name("chap_text")).click();
    driver.findElement(By.name("chap_text")).sendKeys("Capitolo1");
    driver.findElement(By.id("pb_story")).click();
    assertThat(driver.getTitle(), is("BookPad-Storia salvata con successo"));
  }
}
